global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'python_custom_exporter'
    static_configs:
      - targets: ['host.docker.internal:8000'] 
      # host.docker.internal agar container prometheus bisa akses laptop host