name: Advanced CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout Code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Setup Python
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Jalankan Training MLflow Project
    - name: Run MLflow Project (Training)
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        cd MLProject
        python modelling.py

    # Tangkap Run ID 
    - name: Get Latest Run ID
      id: get_run_id
      run: |
        RUN_ID=$(cat MLProject/run_id.txt)
        echo "MLFLOW_RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Captured Run ID: $RUN_ID"

    # Upload Run ID ke GitHub
    - name: Upload Artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: run-id-artifact
        path: MLProject/run_id.txt

    # Login ke Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build & Push Docker Image 
    - name: Build and Push Docker Image
      env:
        MLFLOW_TRACKING_URI: "https://dagshub.com/ayutksnaa/msml-repo.mlflow"
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        echo "Building Docker from DagsHub Run ID: ${{ env.MLFLOW_RUN_ID }}"
        
        # Perintah ini akan menarik model dari DagsHub dan membungkusnya jadi Docker
        mlflow models build-docker \
          -m "runs:/${{ env.MLFLOW_RUN_ID }}/model" \
          -n ${{ secrets.DOCKER_USERNAME }}/water-potability-model:latest \
          --enable-mlserver
        
        echo "Pushing to Docker Hub..."
        docker push ${{ secrets.DOCKER_USERNAME }}/water-potability-model:latest